enum class DaiCommonCameraBoardSocket : int32_t { AUTO = -1, RGB, LEFT, RIGHT };

#define DEPTHAI_ROS_MSGS_MESSAGE_DAICOMMONCAMERABOARDSOCKET_PLUGIN_CLASS_BODY \
    MSGPACK_ADD_ENUM(DaiCameraBoardSocket);
