enum class DaiCameraImageOrientation : int32_t { AUTO = -1, NORMAL, HORIZONTAL_MIRROR, VERTICAL_FLIP, ROTATE_180_DEG };

#define DEPTHAI_ROS_MSGS_MESSAGE_DAICAMERAIMAGEORIENTATION_PLUGIN_CLASS_BODY \
    MSGPACK_ADD_ENUM(DaiCameraImageOrientation);
