enum class CameraImageOrientation : int32_t { AUTO = -1, NORMAL, HORIZONTAL_MIRROR, VERTICAL_FLIP, ROTATE_180_DEG };

#define DEPTHAI_COMMON_MSGS_MESSAGE_CAMERAIMAGEORIENTATION_PLUGIN_CLASS_BODY \
    MSGPACK_DEFINE()

MSGPACK_ADD_ENUM(CameraImageOrientation);